<?php

/**
 * @file
 * Module to expose advanced search enabled status.
 */

use Drupal\eonext_advanced_search\Form\AdvancedSearchConfigForm;

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 *   Theme hook variables array.
 *
 * @see dpl_react_preprocess_dpl_react_app()
 */
function eonext_advanced_search_preprocess_dpl_react_app(array &$variables): void {
  if ('search-header' === $variables['name']) {
    $advanced_search_enabled = \Drupal::service('config.factory')
      ->get(AdvancedSearchConfigForm::CONFIG_ID)
      ->get('advanced_search_enabled');
    /* @phpstan-ignore-next-line  */
    $variables['attributes']['data-advanced-search-enabled'] = json_encode(
      (bool) $advanced_search_enabled
    );
  }
}

/**
 * Implements hook_preprocess_html().
 */
function eonext_advanced_search_preprocess_html(array &$variables): void {
  $advanced_search_config = \Drupal::service('config.factory')
    ->get(AdvancedSearchConfigForm::CONFIG_ID);

  $json_input = $advanced_search_config->get('advanced_search_settings');
  if (!empty($json_input)) {
    $decoded_json = json_decode($json_input, TRUE);
    if ($decoded_json !== NULL) {
      /* @phpstan-ignore-next-line  */
      $variables['attributes']['data-eonext-ext-complex-search'] = json_encode($decoded_json);
    }
  }

}
