<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * @file
 * Library staff logic.
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * The staff paragraphs is an empty paragraph, so set its
 * contents here.
 */
function eonext_staff_preprocess_paragraph__eonext_library_staff(array &$variables): void {
  $view = Views::getView('staff');

  if (!($view instanceof ViewExecutable)) {
    return;
  }

  $view->setDisplay('block_1');
  $view->execute();
  $view_render = $view->render();

  $variables['content'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => [
      'class' => ['eonext-library-staff'],
    ],
    '#value' => \Drupal::service('renderer')->render($view_render),
    '#attached' => [
      'library' => [
        'eonext_staff/general',
      ],
    ],
  ];
}
