<?php

use Drupal\eonext_ext_fields\Form\AdditionalFieldsSettingsForm;

/**
 * @file
 * Extended fields module logic.
 */

function eonext_ext_fields_preprocess_dpl_react_app(array &$variables): void {
  if (in_array($variables['name'], ['material', 'search-result'])) {
    $additional_fields_config = \Drupal::service('config.factory')
      ->get(AdditionalFieldsSettingsForm::CONFIG_ID);

    $cover_override_path = $additional_fields_config->get('cover_override') ?? '';
    if ($cover_override_path) {
      $variables['attributes']['data-eonext-ext-covers'] = $cover_override_path;
    }

    if ('material' === $variables['name'] && !empty($additional_fields_config->get('additional_fields'))) {
      /* @phpstan-ignore-next-line  */
      $variables['attributes']['data-eonext-ext-fields'] = json_encode($additional_fields_config->get('additional_fields'));
    }
  }
}
