<?php

/**
 * @file
 * Primary module hooks for EO Next Translation module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\eonext_translation\Form\TranslationSettingsForm;

/**
 * Implements hook_preprocess_HOOK().
 */
function eonext_translation_preprocess_html(array &$variables): void {

  $translation_settings = \Drupal::config('eonext_translation.settings');
  $translation_type = $translation_settings->get('translation_type');

  $variables['attributes']['data-eonext-translation-type'] = $translation_type;

  if (TranslationSettingsForm::TRANSLATION_TYPE_DRUPAL_TRANSLATE === $translation_type) {
    $languageLinks = \Drupal::service('eonext_translation.service')->getLanguageLinks();
    $variables['attributes']['data-eonext-translation-languages'] = json_encode($languageLinks);
  }

  $translate_footer = \Drupal::config('eonext_translation.footer')->get('translate_footer');
  $footer_settings = \Drupal::service('eonext_translation.service')->getFooterSettings();

  if ($translate_footer) {
    $variables['attributes']['data-eonext-footer'] = json_encode($footer_settings);
  }

}

/**
 * Implements hook_form_alter().
 */
function eonext_translation_form_alter(array &$form, FormStateInterface $form_state, $form_id): void {
  if ($form_id === 'dpl_footer_form') {
    // Add a new submit handler to the footer form.
    $form['#submit'][] = 'eonext_translation_footer_form_submit';
  }
}

/**
 * Submit handler for the footer form.
 */
function eonext_translation_footer_form_submit(array &$form, FormStateInterface $form_state): void {
  \Drupal::service('eonext_translation.service')->saveFooterToConfig();
}

/**
 * Implements hook_preprocess_page().
 */
function eonext_translation_preprocess_page(array &$variables): void {

  $translate_footer = \Drupal::config('eonext_translation.footer')->get('translate_footer');

  if ($translate_footer) {
    $variables['footer_settings'] = \Drupal::service('eonext_translation.service')->getFooterSettings();
  }

}
